In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv("train_data_new.csv")

In [3]:
train_data

             from       to
0          687794  2132718
1          687794   364024
2          687794  3273020
3          687794  4589838
4          687794  4507085
...           ...      ...
24003356  2871896  4272795
24003357  2871896  4600063
24003358  2871896  3612708
24003359  2871896  1579600
24003360  2871896  1079853

[24003361 rows x 2 columns]

In [4]:
combined_df = pd.read_csv("combined_latest.csv")

In [5]:
combined_df

,from,to,Y,SrcIndegree,SrcOutegree,dest_indegree,dest_outdegree,Jaccard_Coefficient,cosine_similarity,Preferential_Attachment_Score
0,134467,118071,0,495,14236,1,0,0.000000,0.000000,14240
1,360019,1209763,0,110,1951,1,0,0.000000,0.000000,1957
2,3471496,2785636,0,13,27,2,0,0.000000,0.000000,66
3,1859805,4116916,0,24,91,1,0,0.000000,0.000000,99
4,2888367,1054895,0,17,39,1,0,0.000000,0.000000,40
...,...,...,...,...,...,...,...,...,...,...
199995,63691,4807146,1,286,13198,3,0,0.000000,0.000000,39675
199996,2882075,1625297,1,668,37638,39,0,0.000847,0.026367,1472913
199997,2150983,4286292,1,337,49384,1,0,0.000000,0.000000,49587
199998,2855754,2169630,1,493,2435,425,2972,0.066382,0.125044,7480473
199999,4739617,1554122,1,991,68888,6,0,0.000073,0.007777,413370

In [6]:
import csv

# Specify the path to your CSV file
csv_file_path = "train_new.csv"

# Initialize an empty list to store the data
data = []

# Open the CSV file and read its contents line by line
with open(csv_file_path, mode='r', encoding='utf-8', newline='') as file:
    csv_reader = csv.reader(file)
    
    # Iterate through each row in the CSV file
    for row in csv_reader:
        # Append the row to the data list
        data.append(row)

# Now, 'data' contains all the rows from the CSV file

## Friends measure

In [6]:
import pandas as pd

# Sample DataFrame with "from" and "to" columns
# data = {'from': [1, 2, 3, 4], 'to': [2, 3, 4, 5]}
# df = pd.DataFrame(data)

# Function to calculate the Friends Measure
def friends_measure(node1, node2, df):
    neighbors1 = set(df[df['from'] == node1]['to'])
    neighbors2 = set(df[df['from'] == node2]['to'])
    
    friends_measure = 1 if neighbors1.intersection(neighbors2) else 0
    
    return friends_measure

# Initialize an empty list to store the Friends Measure for each pair
friends_measures = []

for _, row in combined_df.iterrows():
    from_node = row['from']
    to_node = row['to']
    
    # Calculate the Friends Measure using the function
    friends_score = friends_measure(from_node, to_node, train_data)
    
    # Append the result to the list
    friends_measures.append(friends_score)

# Add the Friends Measure values as a new column to the DataFrame
combined_df['Friends_Measure'] = friends_measures

In [7]:
combined_df

,from,to,Y,SrcIndegree,SrcOutegree,dest_indegree,dest_outdegree,Jaccard_Coefficient,cosine_similarity,Preferential_Attachment_Score,Friends_Measure
0,134467,118071,0,495,14236,1,0,0.000000,0.000000,14240,0
1,360019,1209763,0,110,1951,1,0,0.000000,0.000000,1957,0
2,3471496,2785636,0,13,27,2,0,0.000000,0.000000,66,0
3,1859805,4116916,0,24,91,1,0,0.000000,0.000000,99,0
4,2888367,1054895,0,17,39,1,0,0.000000,0.000000,40,0
...,...,...,...,...,...,...,...,...,...,...,...
199995,63691,4807146,1,286,13198,3,0,0.000000,0.000000,39675,0
199996,2882075,1625297,1,668,37638,39,0,0.000847,0.026367,1472913,0
199997,2150983,4286292,1,337,49384,1,0,0.000000,0.000000,49587,0
199998,2855754,2169630,1,493,2435,425,2972,0.066382,0.125044,7480473,1
199999,4739617,1554122,1,991,68888,6,0,0.000073,0.007777,413370,0

In [8]:
csv_file_path = 'combined_df_final.csv'  # Replace 'your_file.csv' with the desired file name and path

# Save the DataFrame to a CSV file
combined_df.to_csv(csv_file_path, index=False)

## Oppo dirn frnds

In [9]:
import pandas as pd

# Assuming you have a DataFrame df2 with columns 'from' and 'to'

# Initialize an empty list to store the Opposite-Direction Friends Measure for each pair
opposite_direction_friends = []

for _, row in combined_df.iterrows():
    from_node = row['from']
    to_node = row['to']
    
    # Check if there is a reciprocal connection (opposite direction) in your DataFrame
    reciprocal_connection = train_data[(train_data['from'] == to_node) & (train_data['to'] == from_node)].shape[0]
    
    # Convert the result to 1 or 0
    opposite_direction_friends.append(1 if reciprocal_connection > 0 else 0)

# Add the Opposite-Direction Friends Measure as a new column to df2
combined_df['Opposite_Direction_Friends'] = opposite_direction_friends

# Now df2 contains the Opposite-Direction Friends Measure for each pair of nodes

In [10]:
combined_df

,from,to,Y,SrcIndegree,SrcOutegree,dest_indegree,dest_outdegree,Jaccard_Coefficient,cosine_similarity,Preferential_Attachment_Score,Friends_Measure,Opposite_Direction_Friends
0,134467,118071,0,495,14236,1,0,0.000000,0.000000,14240,0,0
1,360019,1209763,0,110,1951,1,0,0.000000,0.000000,1957,0,0
2,3471496,2785636,0,13,27,2,0,0.000000,0.000000,66,0,0
3,1859805,4116916,0,24,91,1,0,0.000000,0.000000,99,0,0
4,2888367,1054895,0,17,39,1,0,0.000000,0.000000,40,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
199995,63691,4807146,1,286,13198,3,0,0.000000,0.000000,39675,0,0
199996,2882075,1625297,1,668,37638,39,0,0.000847,0.026367,1472913,0,0
199997,2150983,4286292,1,337,49384,1,0,0.000000,0.000000,49587,0,0
199998,2855754,2169630,1,493,2435,425,2972,0.066382,0.125044,7480473,1,1
199999,4739617,1554122,1,991,68888,6,0,0.000073,0.007777,413370,0,0

In [11]:
csv_file_path = 'combined_df_final.csv'  # Replace 'your_file.csv' with the desired file name and path

# Save the DataFrame to a CSV file
combined_df.to_csv(csv_file_path, index=False)

In [6]:
combined_df = pd.read_csv("combined_df_final.csv")

In [7]:
combined_df

,from,to,Y,SrcIndegree,SrcOutegree,dest_indegree,dest_outdegree,Jaccard_Coefficient,cosine_similarity,Preferential_Attachment_Score,Friends_Measure,Opposite_Direction_Friends
0,134467,118071,0,495,14236,1,0,0.000000,0.000000,14240,0,0
1,360019,1209763,0,110,1951,1,0,0.000000,0.000000,1957,0,0
2,3471496,2785636,0,13,27,2,0,0.000000,0.000000,66,0,0
3,1859805,4116916,0,24,91,1,0,0.000000,0.000000,99,0,0
4,2888367,1054895,0,17,39,1,0,0.000000,0.000000,40,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
199995,63691,4807146,1,286,13198,3,0,0.000000,0.000000,39675,0,0
199996,2882075,1625297,1,668,37638,39,0,0.000847,0.026367,1472913,0,0
199997,2150983,4286292,1,337,49384,1,0,0.000000,0.000000,49587,0,0
199998,2855754,2169630,1,493,2435,425,2972,0.066382,0.125044,7480473,1,1
199999,4739617,1554122,1,991,68888,6,0,0.000073,0.007777,413370,0,0

In [16]:
import csv

# Specify the path to your CSV file
csv_file_path = "train_new.csv"

# Initialize an empty list to store the data
data = []

# Open the CSV file and read its contents line by line
with open(csv_file_path, mode='r', encoding='utf-8', newline='') as file:
    csv_reader = csv.reader(file)
    
    # Iterate through each row in the CSV file
    for row in csv_reader:
        # Append the row to the data list
        data.append(row)

# Now, 'data' contains all the rows from the CSV file

In [17]:
# Create a directed graph

import networkx as nx
G = nx.Graph()

# Add nodes from the "from" elements in each sublist
for edge in data:
    G.add_node(edge[0])
    

# Add edges from the 2D list
for edge in data:
    from_node = edge[0]
    to_nodes = edge[1:]
    for to_node in to_nodes:
        G.add_edge(from_node, to_node)

In [19]:
pip install community

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Collecting community
  Using cached community-1.0.0b1.tar.gz (2.2 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: Flask in c:\programdata\anaconda3\lib\site-packages (from community) (1.1.2)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from community) (2.28.1)
Requirement already satisfied: click>=5.1 in c:\programdata\anaconda3\lib\site-packages (from Flask->community) (8.0.4)
Requirement already satisfied: Werkzeug>=0.15 in c:\programdata\anaconda3\lib\site-packages (from Flask->community) (2.0.3)
Requirement already satisfied: itsdangerous>=0.24 in c:\programdata\anaconda3\lib\site-packages (from Flask->community) (2.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in c:\programdata\anaconda3\lib\site-packages (from Flask->community) (2.11.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->community) (2022.9.14)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->community) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->community) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->community) (2.0.4)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click>=5.1->Flask->community) (0.4.5)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from Jinja2>=2.10.1->Flask->community) (2.0.1)
Building wheels for collected packages: community
  Building wheel for community (setup.py): started
  Building wheel for community (setup.py): finished with status 'done'
  Created wheel for community: filename=community-1.0.0b1-py3-none-any.whl size=2138 sha256=79b0abd9477c997eebf8c19f91e4ff75cdb1334036483743d8ee8f392b7c5bca
  Stored in directory: c:\users\siddh\appdata\local\pip\cache\wheels\e5\32\7b\aebaa96975f39189b78d7b123cf90e5fd2f0418953833b3043
Successfully built community
Installing collected packages: community
Successfully installed community-1.0.0b1

In [22]:
pip install python-louvain

Defaulting to user installation because normal site-packages is not writeable
Collecting python-louvain
  Using cached python-louvain-0.16.tar.gz (204 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: networkx in c:\programdata\anaconda3\lib\site-packages (from python-louvain) (2.8.4)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from python-louvain) (1.21.5)
Building wheels for collected packages: python-louvain
  Building wheel for python-louvain (setup.py): started
  Building wheel for python-louvain (setup.py): finished with status 'done'
  Created wheel for python-louvain: filename=python_louvain-0.16-py3-none-any.whl size=9395 sha256=ab01116365f1ca05809bc692aa10fac853dda2000520a8effde8fc071426e205
  Stored in directory: c:\users\siddh\appdata\local\pip\cache\wheels\4d\7c\b6\79b198e4ec43f915fbdf967953d48b89a18893b12aa9df0ae2
Successfully built python-louvain
Installing collected packages: python-louvain
Successfully installed python-louvain-0.16
Note: you may need to restart the kernel to use updated packages.

In [7]:
import community

In [8]:
import networkx as nx
import community  # You may need to install python-louvain package

# Assuming you have a graph G
# Use the Louvain method to detect communities
partition = community.best_partition(G)

# Create a dictionary mapping nodes to their communities
node_to_community = {node: community_id for node, community_id in partition.items()}

# Assuming you have a DataFrame df2 with columns 'from' and 'to'
same_community_feature = []

for _, row in combined_df.iterrows():
    from_node = row['from']
    to_node = row['to']
    
    # Check if both nodes belong to the same community
    if node_to_community.get(from_node) == node_to_community.get(to_node):
        same_community_feature.append(1)
    else:
        same_community_feature.append(0)

# Add the Same-Community feature as a new column to df2
combined_df['Same_Community'] = same_community_feature

# Now df2 contains the Same-Community feature for each pair of nodes

MemoryError:

In [ ]:
csv_file_path = 'combined_df_final.csv'  # Replace 'your_file.csv' with the desired file name and path

# Save the DataFrame to a CSV file
combined_df.to_csv(csv_file_path, index=False)

In [ ]:
# import pandas as pd
# import networkx as nx
# import community  # You may need to install the python-louvain package

# # Assuming you have a graph G created from df1
# G = nx.from_pandas_edgelist(df1, source='from', target='to', create_using=nx.Graph())

# # Use the Louvain method to detect communities
# partition = community.best_partition(G)

# # Create a dictionary mapping nodes to their communities in df1
# community_mapping_df1 = partition

# # Now, you can use the same approach to detect communities in df2 based on its own graph

# # Assuming you have another graph G2 created from df2
# G2 = nx.from_pandas_edgelist(df2, source='from', target='to', create_using=nx.Graph())

# # Use the Louvain method to detect communities in df2
# partition2 = community.best_partition(G2)

# # Create a dictionary mapping nodes to their communities in df2
# community_mapping_df2 = partition2

# # Now you can proceed with the code I provided in the previous response to check if nodes in df2 belong to the same community as nodes in df1.

## ADAR

In [18]:
import networkx as nx

# Assuming you have a graph G created from your data
# G = nx.from_pandas_edgelist(df1, source='from', target='to', create_using=nx.Graph())

def adamic_adar_measure(node1, node2, graph):
    if node1 in graph.nodes() and node2 in graph.nodes():
        common_neighbors = list(nx.common_neighbors(graph, node1, node2))
        adamic_adar = 0.0

        for neighbor in common_neighbors:
            neighbor_degree = graph.degree(neighbor)
            if neighbor_degree > 1:
                adamic_adar += 1 / (log(neighbor_degree))
        return adamic_adar 
    else:
        return 0.0

# Calculate Adamic-Adar measures for nodes in df2 with respect to df1
adamic_adar_scores = []

for _, row2 in combined_df.iterrows():
    from_node2 = row2['from']
    to_node2 = row2['to']
    
    aa_measure = adamic_adar_measure(from_node2, to_node2, G)  # Assuming G is your graph
    adamic_adar_scores.append(aa_measure)

# Add the Adamic-Adar scores as a new column to df2
combined_df['Adamic_Adar_Score'] = adamic_adar_scores

# Now df2 contains the Adamic-Adar measure scores for each pair of nodes

In [19]:
combined_df

,from,to,Y,SrcIndegree,SrcOutegree,dest_indegree,dest_outdegree,Jaccard_Coefficient,cosine_similarity,Preferential_Attachment_Score,Friends_Measure,Opposite_Direction_Friends,Adamic_Adar_Score
0,134467,118071,0,495,14236,1,0,0.000000,0.000000,14240,0,0,0.0
1,360019,1209763,0,110,1951,1,0,0.000000,0.000000,1957,0,0,0.0
2,3471496,2785636,0,13,27,2,0,0.000000,0.000000,66,0,0,0.0
3,1859805,4116916,0,24,91,1,0,0.000000,0.000000,99,0,0,0.0
4,2888367,1054895,0,17,39,1,0,0.000000,0.000000,40,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,63691,4807146,1,286,13198,3,0,0.000000,0.000000,39675,0,0,0.0
199996,2882075,1625297,1,668,37638,39,0,0.000847,0.026367,1472913,0,0,0.0
199997,2150983,4286292,1,337,49384,1,0,0.000000,0.000000,49587,0,0,0.0
199998,2855754,2169630,1,493,2435,425,2972,0.066382,0.125044,7480473,1,1,0.0
199999,4739617,1554122,1,991,68888,6,0,0.000073,0.007777,413370,0,0,0.0

In [ ]:
# Calculate Adamic-Adar similarity for nodes 'u' and 'v'
def adamic_adar_similarity(u, v, graph):
    if u in graph.nodes() and v in graph.nodes():
        # Calculate the Adamic-Adar score here
        # ...
        return adamic_adar_score
    else:
        # Handle the case where 'u' or 'v' is not in the graph
        return 0.0  # You can choose to return 0 or another appropriate value

# Example usage
adamic_adar_score = adamic_adar_similarity('node_u', 'node_v', G)

## making test data

In [8]:
test = pd.read_csv("test_data_new.csv")

In [9]:
test

,From,To,Jaccard_Coefficient,SrcIndegree,SrcOutegree,dest_indegree,dest_outdegree,cosine_similarity,Preferential_Attachment_Score
0,3360982,4457271,0.036205,140,1964,93,242,0.107235,542724
1,4761876,4698439,0.000000,69,123,18,0,0.000000,3096
2,4198430,3615486,0.000000,248,6996,30,0,0.000000,212010
3,2945770,747948,0.010352,224,289,62,0,0.030766,26412
4,3950088,3360335,0.025965,161,1309,180,0,0.078795,244980
...,...,...,...,...,...,...,...,...,...
1995,3116985,2415415,0.015544,118,449,673,0,0.030937,338519
1996,265459,842701,0.003686,149,3947,236,1994,0.007753,8052380
1997,2547139,4332939,0.033784,50,131,11,0,0.126511,1562
1998,2366264,1815056,0.008264,10,107,11,0,0.028618,1221
1999,2735577,1232247,0.000000,45,544,10,0,0.000000,5440

In [10]:
import pandas as pd

# Sample DataFrame with "from" and "to" columns
# data = {'from': [1, 2, 3, 4], 'to': [2, 3, 4, 5]}
# df = pd.DataFrame(data)

# Function to calculate the Friends Measure
def friends_measure(node1, node2, df):
    neighbors1 = set(df[df['from'] == node1]['to'])
    neighbors2 = set(df[df['from'] == node2]['to'])
    
    friends_measure = 1 if neighbors1.intersection(neighbors2) else 0
    
    return friends_measure

# Initialize an empty list to store the Friends Measure for each pair
friends_measures = []

for _, row in test.iterrows():
    from_node = row['From']
    to_node = row['To']
    
    # Calculate the Friends Measure using the function
    friends_score = friends_measure(from_node, to_node, train_data)
    
    # Append the result to the list
    friends_measures.append(friends_score)

# Add the Friends Measure values as a new column to the DataFrame
test['Friends_Measure'] = friends_measures

In [11]:
import pandas as pd

# Assuming you have a DataFrame df2 with columns 'from' and 'to'

# Initialize an empty list to store the Opposite-Direction Friends Measure for each pair
opposite_direction_friends = []

for _, row in test.iterrows():
    from_node = row['From']
    to_node = row['To']
    
    # Check if there is a reciprocal connection (opposite direction) in your DataFrame
    reciprocal_connection = train_data[(train_data['from'] == to_node) & (train_data['to'] == from_node)].shape[0]
    
    # Convert the result to 1 or 0
    opposite_direction_friends.append(1 if reciprocal_connection > 0 else 0)

# Add the Opposite-Direction Friends Measure as a new column to df2
test['Opposite_Direction_Friends'] = opposite_direction_friends

# Now df2 contains the Opposite-Direction Friends Measure for each pair of nodes

In [12]:
test

,From,To,Jaccard_Coefficient,SrcIndegree,SrcOutegree,dest_indegree,dest_outdegree,cosine_similarity,Preferential_Attachment_Score,Friends_Measure,Opposite_Direction_Friends
0,3360982,4457271,0.036205,140,1964,93,242,0.107235,542724,1,0
1,4761876,4698439,0.000000,69,123,18,0,0.000000,3096,0,0
2,4198430,3615486,0.000000,248,6996,30,0,0.000000,212010,0,0
3,2945770,747948,0.010352,224,289,62,0,0.030766,26412,0,0
4,3950088,3360335,0.025965,161,1309,180,0,0.078795,244980,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,3116985,2415415,0.015544,118,449,673,0,0.030937,338519,0,0
1996,265459,842701,0.003686,149,3947,236,1994,0.007753,8052380,1,0
1997,2547139,4332939,0.033784,50,131,11,0,0.126511,1562,0,0
1998,2366264,1815056,0.008264,10,107,11,0,0.028618,1221,0,0
1999,2735577,1232247,0.000000,45,544,10,0,0.000000,5440,0,0

In [13]:
csv_file_path = 'test_data_new.csv'  # Replace 'your_file.csv' with the desired file name and path

# Save the DataFrame to a CSV file
test.to_csv(csv_file_path, index=False)